### PR TITLE
fix: prevent NullReferenceException on non-unit barks (fixes #39)

### LINKED ISSUE #39: Barks inaudible
After updating from version `1.2.0` to `1.3.0`, barks have stopped playing.

> I am currently in Verdant Caves, after meeting the first giant. I am on Windows 11, and using the correct ("old") versions of offline natural voices.

I have the `Playback barks` option set to `Enabled`, and the `Only play barks if there is silence` option doesn't seem to make any difference.

### PR DESCRIPTION
**Pull request by BelegCufea**
### Fix: NullReferenceException on Non-Unit Barks

**Fixes #39**

**The Problem:**
The `BarkPlayer_Patch` was assuming that every bark (overtip text) originates from a `Unit`. When interacting with certain environmental triggers, the `__instance.Unit` is null, causing an immediate crash when trying to access `.IsMainCharacter` or `.Gender`.

**The Solution:**
* Added a high-level null check for `__instance.Unit`.
* If a bark comes from a non-unit source (MapObject), the system now defaults to the **Narrator** voice instead of crashing.
* Simplified the internal logic to remove redundant null checks and improve readability.

### CODE REVIEW

File: SpeechMod/Patches/BarkPlayer_Patch.cs [hunk 1]
```diff
@@ -29,25 +29,27 @@ public static void PlayBark_Postfix(EntityOvertipVM __instance, string text, flo
...
-        if (__instance.Unit.IsMainCharacter && Main.Settings.UseProtagonistSpecificVoice)
-        {
-            voice = VoiceType.Protagonist;
-        }
-        else
-        {
-            Gender? gender = null;
-            if (__instance.Unit != null)
-                gender = __instance.Unit.Gender;
+        VoiceType voice = VoiceType.Narrator;
```
Comment (Osmodium) [inline SpeechMod/Patches/BarkPlayer_Patch.cs]:
```suggestion
        var voice = VoiceType.Narrator;

```

File: SpeechMod/Patches/BarkPlayer_Patch.cs [hunk 2]
```diff
@@ -29,25 +29,27 @@ public static void PlayBark_Postfix(EntityOvertipVM __instance, string text, flo
...
+                    Gender.Male => VoiceType.Male,
+                    Gender.Female => VoiceType.Female,
+                    _ => VoiceType.Narrator
+                };
+            }
         }
 
         Main.Speech.SpeakAs(text, voice);
+
+        Main.Speech.SpeakAs(text, voice);
```
Comment (Osmodium) [inline SpeechMod/Patches/BarkPlayer_Patch.cs]: Extra `Main.Speech.SpeakAs(text, voice);` unecessary
```suggestion
```

**Review by Osmodium — CHANGES_REQUESTED** [review]
Good catch!
Made some suggested changes for you.

**Review by Osmodium — APPROVED** [review]
